### ISSUE TITLE
Mise en ligne des sites Web par défaut sur Deuxfleurs

### ISSUE THREAD

**Issue by arnaudlevy** [noesya/osuny#1234]
## github
- [x] Clonage du template (utiliser l'identifiant de l'instance, plus un slug du nom du site ?)
- [x] Ajout de la Github action dans le template
- [x] Publication de la configuration Hugo

## deuxfleurs
- [x] Création du bucket
- [x] Premier appel pour générer le certificat
- [x] Génération de la config
- [x] Possibilité de changer le domaine associé (quand le DNS est pointé)

**Comment by arnaudlevy** [comment]
Dans `config/production/config.yaml` on peut mettre 
```
deployment:
  targets:
    - name: "production"
      URL: "s3://[id du bucket garage]?endpoint=garage.deuxfleurs.fr&s3ForcePathStyle=true&region=garage"
```
