### ISSUE TITLE
Précalculer le titre par défaut des blocs pages

### ISSUE THREAD

**Issue by arnaudlevy** [noesya/osuny#1423]
Si pas des titres et page principale, utiliser le titre de la page principale

**Comment by alexisben** [comment]
## Page principale présente

### Titre du bloc présent

Comportement similaire aux autres blocs : on conserve le titre du bloc et son ranking 

### Pas de titre au bloc

Fallback sur le titre de la page principale : rank.self doit être précisé et rank.children = rank.self + 1

## Pas de page présente

### Titre du bloc présent

Comportement similaire aux autres blocs : on conserve le titre du bloc et son ranking 

### Pas de titre au bloc

Pas de fallback ```rank.self: false```

**Comment by arnaudlevy** [comment]
Voilà le code avant :
``` 
  - kind: block
    template: pages
    title: >-
      Avec titre de bloc
    position: 2
    ranks:
      self: 2
      children: 3
    data:
      page: 
        path: "/fr/new-path/"
        slug: "new-path"
        file: "content/fr/pages/new-path/_index.html"
      show_main_description: true
      show_descriptions: true
      show_images: true
      layout: grid
      pages:
        - path: "/fr/new-path/page-enfant/"
          slug: "page-enfant"
          file: "content/fr/pages/new-path/page-enfant/_index.html"
          external: false


  - kind: block
    template: pages
    title: >-
      
    position: 3
    ranks:
      self: false
      children: 2
    data:
      page: 
        path: "/fr/new-path/"
        slug: "new-path"
        file: "content/fr/pages/new-path/_index.html"
      show_main_description: true
      show_descriptions: true
      show_images: true
      layout: grid
      pages:
        - path: "/fr/new-path/page-enfant/"
          slug: "page-enfant"
          file: "content/fr/pages/new-path/page-enfant/_index.html"
          external: false


  - kind: block
    template: pages
    title: >-
      Avec titre de bloc
    position: 4
    ranks:
      self: 2
    data:
      show_main_description: false
      show_descriptions: false
      show_images: false
      layout: grid
      pages:


  - kind: block
    template: pages
    title: >-
      
    position: 5
    ranks:
      self: false
    data:
      show_main_description: false
      show_descriptions: false
      show_images: false
      layout: grid
      pages:
```
