### ISSUE TITLE
Bloc Agenda : mode catégorie

### ISSUE THREAD

**Issue by alexisben** [noesya/osuny#1544]
Dans le bloc agenda, quand on est en mode catégorie, le champ category reste vide .

Le bloc testé dans example.osuny : 
[https://demo.osuny.org/admin/communication/blocks/50f160c4-58d7-4cd5-9fc5-df7d909158b7/edit?lang=fr&website_id=c48c69c3-028f-4719-9a3c-40b40f285ed0](https://demo.osuny.org/admin/communication/blocks/50f160c4-58d7-4cd5-9fc5-df7d909158b7/edit?lang=fr&website_id=c48c69c3-028f-4719-9a3c-40b40f285ed0
)
![image](https://github.com/noesya/osuny/assets/4630530/de0df96c-9aad-4280-ad62-69467d19f5b5)

dans [content/fr/pages/blocks/blocs-de-liste/agenda-1/_index.html
](https://github.com/noesya/osuny-example/blob/2f29fc59788b7f7405da1f907d0a1615e5c94639/content/fr/pages/blocks/blocs-de-liste/agenda-1/_index.html)

``` 
data:
      mode: category
      layout: large
      description: >-
        

      no_event_message: >-
        

      show_summary: true
      show_category: true
      show_status: true
      category: ""
      events:
        - path: "/fr/agenda/2024-02-03-charbel-joseph-h-boutros-the-sun-is-my-only-ally/"
          file: "content/fr/events/2024-02-03-charbel-joseph-h-boutros-the-sun-is-my-only-ally.html"
        - path: "/fr/agenda/2024-02-03-anne-charlotte-finel-respiro/"
          file: "content/fr/events/2024-02-03-anne-charlotte-finel-respiro.html"
```
