### ISSUE TITLE
Portfolio

### ISSUE THREAD

**Issue by alexisben** [noesya/osuny#1716]
### Le format du block n'est pas iso avec le block posts ### : 

Block posts :

```
- kind: block
    template: posts
    title: >-
      Toutes les actualités - Grand
    ranks:
      self: 2
      children: 3
    data:
      mode: all
      all: true
      layout: large
      posts:
        - "2023/2023-03-04-referentiel-general-decoconception-de-services-numeriques-rgesn"
        - "2023/2023-08-02-proposition-de-loi-relative-a-la-responsabilite-des-medias-dans-le-traitement-des-enjeux-environneme"
        - "2022/2022-12-01-les-cooperatives-energetiques-citoyennes-des-modeles-originaux-pour-plus-de-sobriete"
[11 h 18](https://noesya.slack.com/archives/C02BFLYMLHY/p1710757118605489)
```

Block projects :

```
  - kind: block
    template: projects
    title: >-
      Les projet
    ranks:
      self: 2
      children: 3
    data:
      mode: all
      all: true
      layout: grid
      projects:
        - slug: "degrowth-journal"
          file: "projects/2023-degrowth-journal.html"
        - slug: "dictionnaire-du-climat"
          file: "projects/2023-dictionnaire-du-climat.html"
        - slug: "alt-shift"
          file: "projects/2022-alt-shift.html"
```
